# Generated by Django 6.0.1 on 2026-01-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('DEFAULT', 'all'), ('HORROR', 'horror'), ('COMEDY', 'comedy'), ('SCIFI', 'scifi')], default='DEFAULT', max_length=10),
        ),
    ]
