# Generated by Django 6.0.1 on 2026-01-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0004_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('default', 'default'), ('horror', 'horror'), ('comedy', 'comedy'), ('scifi', 'scifi')], default='default', max_length=10),
        ),
    ]
