# Generated by Django 6.0.1 on 2026-02-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0006_remove_book_sinopsis_book_added_by_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
